services:
  - type: web
    plan: free
    name: Cloud_Plateforme_TP3
    runtime: node
    repo: https://github.com/WassimTorjmen/Plateforme_Cloud_TP3
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Cloud_Plateforme_TP3_DB
          property: connectionString

databases:
  - name: Cloud_Plateforme_TP3_DB
    plan: free
    region: frankfurt
    user: wassim
    password: wassim123
    envVars:
      - key: POSTGRES_DB
        value: Cloud_Plateforme_TP3_DB
      - key: POSTGRES_USER
        value: wassim
      - key: POSTGRES_PASSWORD
        value: wassim123
