services:
  - type: web
    plan: free
    name: Cloud_Plateforme_TP3_Web
    runtime: node
    region : frankfurt
    repo: https://github.com/WassimTorjmen/Plateforme_Cloud_TP3.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Cloud_Plateforme_TP3_DB
          property: connectionString

databases:
  - name: Cloud_Plateforme_TP3_DB
    plan: free
    region: frankfurt
    
